### ISSUE TITLE
no issue

### ISSUE THREAD

**Issue by letrend** [robosavvy/vive_ros#15]
For the current steamvr you only need to run the following command to run your code
~/.steam/ubuntu12_32/steam-runtime/run.sh devel/lib/vive_ros/vive_node

thanks a lot for this package. we are using it to compare our [custom vive tracking](https://hackaday.io/project/19570-htc-vive-lighthouse-custom-tracking) with steamVR

**Comment by lcluz** [comment]
thanks.
