### ISSUE TITLE
current status of vive_ros

### ISSUE THREAD

**Issue by iory** [robosavvy/vive_ros#16]
- get 3D position/rotation of HMD, controller, tracker https://github.com/robosavvy/vive_ros
- Visualize HDMI video stream to HMD monitor #12
- Obtain button signal of controllers #5 
- Capture images on HMD camera None

Cc: @k-okada @ishiguroJSK

**Comment by k-okada** [comment]
FYI: @sanketrahul

**Comment by sanketrahul** [comment]
@iory : I am getting error of https://github.com/robosavvy/vive_ros/issues/10 . By any chance did you encountered this error for your installation. If yes then please suggest ways to tackle it?
CC: @k-okada

**Comment by ishiguroJSK** [comment]
How did you install required things (openvr, vive_ros)?
The master branch of this repository is a bit outdated, and there are also several updates about SteamVR installation.
(you can also check latest updates in https://github.com/ValveSoftware/SteamVR-for-Linux/issues)
Anyway first, you would better to confirm if you can run SteamVR successfully or not with your PC environment.

To @iory , be careful to confirm with your PC environment, because recently I was forced to update several things around the nvidia driver and the vulkan library.
Once you boot the SteamVR with online, you'll encounter some error.
(see https://github.com/ValveSoftware/SteamVR-for-Linux/issues/104)

**Comment by sanketrahul** [comment]
@ishiguroJSK 
I have installed openvr: git clone https://github.com/ChristophHaag/openvr.git
vive_ros: https://github.com/robosavvy/vive_ros
I am using Ubuntu 16.04 and ROS: Kinetic 
I am able to run steamvr on my desktop. But one issue comes is that display is not done on headset rather on the desktop monitor only. 
Can you tell/point me what changes you did for nvidia driver and vulkan library? I think that may be the issue.

**Comment by ishiguroJSK** [comment]
> But one issue comes is that display is not done on headset rather on the desktop monitor only.

This feature is called nvidia's "direct-mode". that treats HMD devices as not just a monitor but HMD.
So, with no application using HMD, the HMD will be black out. This is correct.

Can you play SteamVR home or any other games with your SteamVR?
Is there no error code like 306 or 307 in your environment?
If so, you can go next step.

**Comment by ishiguroJSK** [comment]
In short, I install the latest vulkan from source, and edit a config file.
I recommend you to uninstall libvulkan (if you have).
You can confirm the vulkan is working or not with `vulkaninfo` command.
> I encountered same problem recently (2018/05) , and I managed to solve it on my PC.
> A while ago, I could run SteamVR with no problem at Ubuntu14.04 QuadroM4000M, driver 387.12, vulkan 1.1.70, direct-mode.
> Since latest steam update, the error occured and I tried to catch up latest requirement.
> As you can see in 
> https://github.com/moon-wreckers/vive_tracker
> they install latest vulkan from the site.
> https://vulkan.lunarg.com/sdk/home#linux
> and I edited /usr/share/vulkan/nvidia_icd.json as
> ```
> {
>     "file_format_version" : "1.0.0",
>     "ICD": {
>         "library_path": "libGLX_nvidia.so.0",
>         "api_version" : "1.1.73"
>     }
> }
> ```
> With this method, I could solve my problem at Ubuntu14.04 QuadroM4000M, driver 396.24, vulkan(1.1.73), direct-mode.
> (However with my another PC at Ubuntu14.04 QuadroK2100M, driver 396.24, vulkan 1.1.73,
> the direct-mode doesn't work and SteamVR doesn't work yet.)

**Comment by sanketrahul** [comment]
Yes I am getting 306 error when I run a game.

**Comment by ishiguroJSK** [comment]
If so, the solution above may solve your error.
But, I don't know how the latest nvidia driver version is, because we are using 14.04.
After doing the procedure above, you would better confirm the `vulkaninfo` command indicates that your environment is working with latest vulkan.

**Comment by sanketrahul** [comment]
Thanks @ishiguroJSK That error went away with installation of latest vulkan. But still when I run Steam VR Home, it says: Failed to launch SteamVR Home.

**Comment by ishiguroJSK** [comment]
what is the error saying in detail?
have you ever succeeded playing games with your pc (includes windows OS)?
We also have several pc that can't run htc vive because of hardware
specification



2018年5月22日(火) 12:42 sanketrahul <notifications@github.com>:

**Comment by sanketrahul** [comment]
I can play games in ubuntu also in steamvr.
The error for VR Home only says: Failed to launch SteamVR Home.

**Comment by ishiguroJSK** [comment]
I don't know what happen on steamvr home,
but if you can play other vr games now.
you have possibility to use vive_ros.

2018年5月22日(火) 13:02 sanketrahul <notifications@github.com>:

**Comment by ishiguroJSK** [comment]
Sorry for late reply,
First, you would better compile the openvr from official ver https://github.com/ValveSoftware/openvr on ~/openvr
And the latest feature of vive_ros from us is here https://github.com/ishiguroJSK/vive_ros/tree/vulkan-dev-2018 (this is my branch, not master).
If you succeeded both, you can run vive_ros with `roslaunch vive_ros vive.launch`

**Comment by sanketrahul** [comment]
@ishiguroJSK Thanks for your reply!  I just have latest version of vulkan. And then I went and ran vive_ros and it worked. But still issues with headset is there. But I think for my work I need vive_ros working only.
