### ISSUE TITLE
cannot launch node of type

### ISSUE THREAD

**Issue by Nightless91** [robosavvy/vive_ros#17]
Problem:

I have built vive_ros from source and I got some sort of path error or node error. Not sure, pretty new to ROS.

ERROR: cannot launch node of type [vive_ros/launch_servervr.sh]: vive_ros
ROS path [0]=/opt/ros/kinetic/share/ros
ROS path [1]=/opt/ros/kinetic/share

so where is the problem? I've strictly followed the installation instrucions on the install.md data.
I've read a lil bit about the catkin workspace..is it possible the reason of the problem?

**Comment by lcluz** [comment]
did you source your workspace?
