### ISSUE TITLE
libdbus-1.so.3 & /libgpg-error.so.0: no version information available

### ISSUE THREAD

**Issue by sanketrahul** [robosavvy/vive_ros#18]
I have installed OpenVR SDK v1.0.5 version from  https://github.com/ValveSoftware/openvr for some other project. I am getting following error:
/home/baxter2/.local/share/Steam/steamapps/common/SteamVR/tools/bin/linux64/vrmonitor:
 /home/baxter2/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/lib/x86_64-linux-gnu/libdbus-1.so.3: no version information available (required by /usr/lib/x86_64-linux-gnu/libpulse.so.0)
/home/baxter2/.local/share/Steam/steamapps/common/SteamVR/tools/bin/linux64/vrmonitor: /home/baxter2/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/lib/x86_64-linux-gnu/libgpg-error.so.0: no version information available (required by /lib/x86_64-linux-gnu/libgcrypt.so.20)

Also the detailed error is posted: https://gist.github.com/sanketrahul/10a325667ffde7100ec8058272864872
My SteamVR version: SteamVR build from January 3rd, 2017 using download_depot 250820 250823 1008772584334738762

cc: @k-okada @ishiguroJSK

**Comment by ishiguroJSK** [comment]
Are you now using master branch of vive_ros with latest OpenVR?
The master branch of vive_ros is outdated and not compatible with latest official OpenVR.
Try ChristophHaag's old OpenVR or our latest vive_ros branch https://github.com/ishiguroJSK/vive_ros/tree/vulkan-dev-2018.

**Comment by sanketrahul** [comment]
@ishiguroJSK  I have to use specific openvr version i,e. OpenVR SDK v1.0.5 version. I tried to use your suggested vive_ros version. But I am still getting same error.

**Comment by ishiguroJSK** [comment]
I checked about OpenVR 1.0.5 and I found its last commit was in Dec 2016.
As long as we are working with latest SteamVR, anything could happen with the old OpenVR, because OpenVR calls many SteamVR functions.
And unfortunately, there is no way to rollback the SteamVR version.
(If you still have any other SteamVR environment installed in Dec 2016, and if you haven't updated it yet, you have a chance to rollback SteamVR manually by copying corresponding files)

**Comment by sanketrahul** [comment]
@ishiguroJSK  
Yes I have manually copied previous version of SteamVR build from January 3rd, 2017 to the SteamVR folder.

**Comment by ishiguroJSK** [comment]
I see.
(The "download_depot" is news to me. Thanks)
As long as I read the error, I guess the versions of the library files in `/usr/lib/x86_64-linux-gnu` and `.local/share/Steam/ubuntu12_32/steam-runtime/amd64/lib/x86_64-linux-gnu/` are missmatch.
You said you are using Ubuntu 16.04, but it was just released in Apr 2016.
This is just my guess, the SteamVR built in Dec 2016 is not compatible with system libraries in built in Apr 2016 isn't it?
Or you updated the system libraries and they were changed to incompatible with the old SteamVR library files.

**Comment by ishiguroJSK** [comment]
First of all, can you launch the old SteamVR correctly with your environment?

**Comment by sanketrahul** [comment]
Yes I cannot launch old SteamVR with my environment :(

**Comment by ishiguroJSK** [comment]
I guess there is no way to rollback the SteamVR so old in Ubuntu16.04 ...

**Comment by sanketrahul** [comment]
You can use following to go some previous SteamVR version:
The plugin was developed using the SteamVR build from January 3rd, 2017. Later versions might brake the plugin. To get older versions of SteamVR, install the Steam command line tool: sudo apt-get install steamcmd. Start it with steamcmd and use following command:

    login
    download_depot 250820 250823 1008772584334738762 This downloads the SteamVR build from January 3rd, 2017. 250820 is the ID of SteamVR, 250823 the ID of the linux depot, and 1008772584334738762 the ID of the correct build. The command line tool will output the path, where it has downloaded the files to, e.g. /home/username/.steam/steamcmd/linux32\steamapps\content\app_250820\depot_250823. Note that Steam was developed for Windows and did not learn that Unix uses slashes for directories. Copy the files into the SteamVR directory you noted earlier, e.g. cp -r /home/username/.steam/steamcmd/linux32/steamapps/content/app_250820/depot_250823/ /home/username/.steam/steam/steamapps/common/SteamVR/*. Merge and replace existing files.
