### ISSUE TITLE
ROS Melodic - `ZLIB_1.2.9' not found (required by  /usr/lib/x86_64-linux-gnu/libpng16.so.16)

### ISSUE THREAD

**Issue by mortaas** [robosavvy/vive_ros#19]
ROS Melodic is probably not supported by this package yet, but it seems like it could be doable if the library issues are fixed. I currently get the following error when trying to launch the vive.launch from the vulkan-dev-2018 branch with the newest OpenVR SDK (1.0.15) in ROS Melodic:
```
~/catkin_ws/devel/lib/vive_ros/vive_node: ~/.steam/ubuntu12_32/steam-
runtime/amd64/lib/x86_64-linux-gnu/libz.so.1: version `ZLIB_1.2.9' not found (required by 
/usr/lib/x86_64-linux-gnu/libpng16.so.16)
================================================================================
REQUIRED process [vive_node-1] has died!
process has died [pid 8603, exit code 1, cmd ~/catkin_ws/devel/lib/vive_ros/vive_node 
__name:=vive_node __log:=~/.ros/log/8923e978-7451-11e8-8ce2-
4cedfb5e997e/vive_node-1.log].
log file: ~/.ros/log/8923e978-7451-11e8-8ce2-4cedfb5e997e/vive_node-1*.log
Initiating shutdown!
================================================================================
```
_The log file is empty_

I tried the solution mentioned for a similar problem (https://ubuntuforums.org/showthread.php?t=2375927), but it didn't seem to work for this particular case.

**Comment by lcluz** [comment]
Did you solve this issue? We don't use ROS Melodic yet, so it is not a priority for us to have this running on it.

**Comment by mortaas** [comment]
I did solve this issue, it is not related to melodic, but the way that this node runs through the Steam runtime. I think this package was made before SteamVR got proper linux support, which can result in library discrepancies with newer versions of OpenVR and SteamVR.

The solution is to run the node through the Steam runtime as shown here (RUNTIME REQUIREMENTS):
[https://github.com/ValveSoftware/SteamVR-for-Linux](https://github.com/ValveSoftware/SteamVR-for-Linux)

`~/.steam/steam/ubuntu12_32/steam-runtime/run.sh ./my_steamvr_app`

**Comment by lcluz** [comment]
perfect! thank you very much.
I will close the issue.
