### ISSUE TITLE
Compatibility with Base Station 2.0

### ISSUE THREAD

**Issue by DaniGarciaLopez** [robosavvy/vive_ros#24]
Currently, all base stations 1.0 are out of stock. We are planning to buy a base station 2.0 and a tracker for our lab. Does anyone tried it and can tell us if it works? As far as I know, the tracker has to be "2018" version but it should work. I would like to be sure before buying.

**Comment by ishiguroJSK** [comment]
Sorry, I have not got the 2.0 yet.
I think if the OpenVR works well with the Steam VR 2.0,
it's not so much hard to modify this repo to work.

**Comment by korbinianbauer** [comment]
Can confirm SteamVR Base Stations 2.0 work without changes.
