### ISSUE TITLE
Publish position of controller not via /tf but rostopic

### ISSUE THREAD

**Issue by dmitterberger** [robosavvy/vive_ros#28]
The tracking of the controller works great in ros and correctly visualizes in rviz.
But - I am currently using roslibpy in ironpython in Rhinoceros (3d modelling program) and I have some issues with receiving tf messages properly. (must be a program internal networking issue). Any other rostopic is no problem -  Is there a possibility to send the current pose of each controller as a rostopic rather than a tf data tree?

I would be very thankful for any hint

**Comment by ishiguroJSK** [comment]
Indeed, vive_ros itself doesn't publish PoseStamped now.
One solution is converting TF to PoseStamped before rosbridge tunneling.
We use simple python code like this,
https://github.com/jsk-ros-pkg/jsk_common/blob/master/jsk_topic_tools/scripts/tf_to_pose.py

and it can be written on your launch file like this (sudo apt install ros-melodic-jsk-topic-tools)
```
  <node pkg="jsk_topic_tools" type="tf_to_pose.py" name="tf_to_pose">
    <remap from="~output" to="my_controller_pose_topic"/>
    <rosparam>
      src_frame: /world_vive
      dst_frame: /controller_LHR*********
      rate: 100
    </rosparam>
  </node>
```

The other solution would be implementing the PoseStamped publisher on this vive_ros.

**Comment by dmitterberger** [comment]
Thanks a lot - this is working perfectly.
