### ISSUE TITLE
HTC Vive double vision when streaming stereo camera images

### ISSUE THREAD

**Issue by mariocorsanici** [robosavvy/vive_ros#29]
Hi,

I am trying to use vive_ros to project the video coming from a ZEDM stereo camera into an HTC Vive HMD. I am able to stream the images but the objects far from me are doubled. Does anyone know how to fix this issue? Thanks

**Comment by mariocorsanici** [comment]
Shifting the image close together using opencv solved the issue

**Comment by buckleytoby** [comment]
@mariocorsanici could you explain more what you did? I'm experiencing a similar issue.
