### ISSUE TITLE
Is the headset actually required for the controller tracking?

### ISSUE THREAD

**Issue by kubelvla** [robosavvy/vive_ros#4]
Hi and thanks for your effort,
this is great. One question, if we order two base stations, a controller and link box, will it work without the headset? It seems that it is already possible to buy the accessories separately at the htc vive shop...

Thanks again for pointing us to a Vicon for $300 :), best
Vladimir Kubelka

**Comment by vmatos** [comment]
As far as I understand, yes. When SteamVR doesn't detect the HMD, it won't launch.

**Comment by kubelvla** [comment]
Oh... We already bought the Oculus for the lab, now I will have to explain why we need another VR headset :D
Thanks anyway...

**Comment by eric-schleicher** [comment]
SteamVR setting allow for startup without the HMD.  the catch is that that the PRE and production VIVE have the bluetooth radios in the Headset.   so you can disable the requirement for the headset in the vrsettings.json file, but you have to have a steam dongle to stand in for the radio in the HMD.
