### ISSUE TITLE
vive_ros: Universal ID invalid

### ISSUE THREAD

**Issue by abhigoudar** [robosavvy/vive_ros#6]
I am trying to get the HTC vive running using vive_ros. I am facing a couple of issues:
1. The server complains of broken pipes immediately after running the vive node (this is done after launching the vrserver). 
2. I noticed that the default 'config' was being used for play area and universe ID. There was a printout for invalid 'Universe ID'. Looking at the windows counterpart revealed a .vrchap file which seems to contain the 'play-area' specification. Is there a way to tell the ros node to use specific config files ? 

Thank you.

**Comment by vmatos** [comment]
1. Yes it does. don't know the  cause. but has been working
2. Haven't looked into that.
