### ISSUE TITLE
Ubuntu 16.04

### ISSUE THREAD

**Issue by danbodily** [robosavvy/vive_ros#7]
This is awesome! Just a comment that steam or something else wasn't playing nice on 16.04 whereas everything on 14.04 worked nicely.

**Comment by eric-schleicher** [comment]
Oh.  I'm about to try it on 16.04.  Will update here if the updates to steamVR beta for linux address it running on 16.04

**Comment by lcluz** [comment]
Just to close this issue and say that it is working on ubuntu 16.04.
